name: Android Debug Build

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
        # continue-on-error: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ./
          npm install

      # - name: Set up Android SDK
      #   uses: android-actions/setup-android@v2
      #   with:
      #     api-level: 35
      #     build-tools: 35.0.0

      #* Make sure to make gradlew executable to git
      # cd android && git update-index --chmod=+x gradlew

      # - name: Build Debug APK

      #   run: ./gradlew assembleDebug
      #   working-directory: android

      - name: Build Debug APK
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android && ./gradlew assembleDebug

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
